# Generated by Django 2.2.7 on 2020-04-24 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=1200)),
                ('image', models.ImageField(upload_to='product_image')),
                ('real_price', models.IntegerField()),
                ('dicount_price', models.IntegerField()),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category')),
            ],
        ),
    ]
