# Generated by Django 2.2.7 on 2020-04-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
