# Generated by Django 2.2.7 on 2020-04-24 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_products_publish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='catagory',
            new_name='category',
        ),
    ]
