# Generated by Django 2.2.7 on 2020-04-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200424_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='dicount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100000, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='real_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100000, null=True),
        ),
    ]
