# Generated by Django 2.2.7 on 2020-04-27 21:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200428_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='dicount_price',
            field=models.IntegerField(default=55),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='real_price',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
