# Generated by Django 2.2.7 on 2020-04-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_all',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
