# Generated by Django 2.2.7 on 2020-04-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200426_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_all',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
