# Generated by Django 2.2.7 on 2020-04-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_all_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_all',
            old_name='address1',
            new_name='Address1',
        ),
        migrations.RenameField(
            model_name='order_all',
            old_name='address2',
            new_name='Address2',
        ),
        migrations.RenameField(
            model_name='order_all',
            old_name='city',
            new_name='City',
        ),
        migrations.RenameField(
            model_name='order_all',
            old_name='pincode',
            new_name='Pincode',
        ),
        migrations.RenameField(
            model_name='order_all',
            old_name='state',
            new_name='State',
        ),
        migrations.RemoveField(
            model_name='order_all',
            name='name',
        ),
        migrations.AddField(
            model_name='order_all',
            name='Contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order_all',
            name='Email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order_all',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
