# Generated by Django 2.2.7 on 2020-04-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200426_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_all',
            name='Email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
