# Generated by Django 2.2.7 on 2020-04-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20200428_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_all',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
