# Generated by Django 2.2.7 on 2020-05-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20200428_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_all',
            name='status',
            field=models.CharField(blank=True, choices=[('success', 'success'), ('fail', 'fail'), ('initial', 'initial')], default='initial', max_length=100, null=True),
        ),
    ]
