# Generated by Django 2.2.7 on 2020-05-28 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_all_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_all',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('fail', 'fail'), ('initial', 'initial')], default='initial', max_length=100),
        ),
    ]
